### ISSUE TITLE
Error "spawn npm ENOENT" during test process running on OS Windows 11

### ISSUE THREAD

**Issue by IuliiaStrakhova** [hereticjsorg/heretic#56]
**Steps for reproduce:**

- Open project in VS Code on Windows 11
- Run command "npm test" in terminal

**Actual result:** tests partially failed:
![image](https://user-images.githubusercontent.com/77919635/222984482-ff2b5831-8130-415a-93a8-a8f47b39d8b6.png)
src/core/tests/10-build.test.js - spawn npm ENOENT" error message:
![image](https://user-images.githubusercontent.com/77919635/222984549-e02cb8ae-e0ca-4454-9b58-b403c523ca4a.png)
here is dev mode - pls see on screenshot, the same for the production mode;

src/core/tests/20-server.test.js - 
![image](https://user-images.githubusercontent.com/77919635/222984696-fc1c4561-f337-4c7e-9878-b5b1b6cbc539.png)
![image](https://user-images.githubusercontent.com/77919635/222984722-20d1afc3-807d-4131-9072-7282dea36549.png)
![image](https://user-images.githubusercontent.com/77919635/222984750-503d7799-779b-462e-8b62-35fbcd05e5eb.png)

**Root cause** seems to be the same as in https://github.com/hereticjsorg/heretic/issues/53
After changing "npm run server" to "npm.cmd run server" in

- src/core/tests/10-build.test.js
- src/core/tests/20-server.test.js
- testHelpers.js

src/core/tests/10-build.test.js - passed:
![image](https://user-images.githubusercontent.com/77919635/222984980-aa347517-1eb7-48be-9885-45db689f7620.png)
src/core/tests/20-server.test.js - still fails, but with different error:
![image](https://user-images.githubusercontent.com/77919635/222985093-dc4795fc-104f-4c0a-91fe-dc29e56bc28e.png)
![image](https://user-images.githubusercontent.com/77919635/222985174-fe9a9d06-fc4b-4f15-8af0-c249acd38a64.png)
appeared issues with asynchronous operations.

**Comment by hereticjsorg** [comment]
Fixed by #57
